### ISSUE TITLE
installation failures

### ISSUE THREAD

**Issue by shime** [arschmitz/ember-cli-standard#1]
```
$ ember install ember-cli-standard
Installed packages for tooling via npm.
installing ember-cli-standard
  uninstall package ember-cli-eslint
Uninstalled packages for tooling via npm.
  uninstall package ember-cli-jshint
Uninstalled packages for tooling via npm.
No JSHint or ESLint config files found.
? Would you like to run standard format to upate current code to standard? (Use arrow keys)
❯ Yes
  Not now

Remaining issues we couldnt fix for you...

/bin/sh: standard: command not found

Installed addon package.
```

Looks like standard was not installed as a dependency?

**Comment by arschmitz** [comment]
Hi thank you for reporting this just added the fix feature and forgot it will require a direct dependency not just the `broccoli-standard`  implementation. There are 2 problems here first is yes that dependency is missing, but also that i'm executing the global standard instead of one from dependency. 

Ill try to get this fixed tonight and a patch for it out

**Comment by arschmitz** [comment]
this is fixed in latest version
